name: time zone

on:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: show date in tokyo
        run: |
          date +"%Y-%m-%d %H:%M"
        env:
          TZ: "-9"
