name: Issue Opened

on:
  issues:
    types:
      - opened

jobs:
  issue-opened:
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to issue
        uses: technote-space/assign-author@v1
